-- 0010_trade_intents.sql
-- Phase 1: introduce trade_intents table to persist actionable trade metadata extracted from signals.
CREATE TABLE IF NOT EXISTS trade_intents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_id BIGINT UNIQUE REFERENCES signals(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  market TEXT NOT NULL,
  size_mode TEXT NOT NULL,
  size_value NUMERIC NOT NULL,
  max_slippage_bps INTEGER,
  deadline_ts BIGINT,
  intent_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trade_intents_signal_id ON trade_intents(signal_id);
