-- Create the users table
CREATE TABLE IF NOT EXISTS users (
  telegram_id BIGINT PRIMARY KEY,
  username TEXT,
  trade_amount FLOAT4 DEFAULT 25.0,
  trade_token TEXT DEFAULT 'USDC',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the settings table (this might be redundant since trade_amount is in users table)
CREATE TABLE IF NOT EXISTS settings (
  user_id BIGINT PRIMARY KEY REFERENCES users(telegram_id) ON DELETE CASCADE,
  trade_amount DECIMAL DEFAULT 25.0
);

-- Create the subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
  id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_telegram_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
  broadcaster_username TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Create policies to allow service role to access all data
-- (Since we're using the service role key, these policies will allow full access)
CREATE POLICY "Service role can do everything on users" ON users
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role can do everything on settings" ON settings
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Service role can do everything on subscriptions" ON subscriptions
  FOR ALL USING (true) WITH CHECK (true);
